// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: stub/scheduling.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerClient interface {
	// Register a new model service
	RegisterModelService(ctx context.Context, in *RegisterModelServiceRequest, opts ...grpc.CallOption) (*RegisterModelServiceResponse, error)
	// Scale a model service
	ScaleModelService(ctx context.Context, in *ScaleModelServiceRequest, opts ...grpc.CallOption) (*ScaleModelServiceResponse, error)
	// Unregister a model service
	UnregisterModelService(ctx context.Context, in *UnregisterModelServiceRequest, opts ...grpc.CallOption) (*UnregisterModelServiceResponse, error)
	// Register a new GPU instance
	RegisterGPUInstance(ctx context.Context, in *RegisterGPUInstanceRequest, opts ...grpc.CallOption) (*RegisterGPUInstanceResponse, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) RegisterModelService(ctx context.Context, in *RegisterModelServiceRequest, opts ...grpc.CallOption) (*RegisterModelServiceResponse, error) {
	out := new(RegisterModelServiceResponse)
	err := c.cc.Invoke(ctx, "/scheduler.Scheduler/RegisterModelService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ScaleModelService(ctx context.Context, in *ScaleModelServiceRequest, opts ...grpc.CallOption) (*ScaleModelServiceResponse, error) {
	out := new(ScaleModelServiceResponse)
	err := c.cc.Invoke(ctx, "/scheduler.Scheduler/ScaleModelService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) UnregisterModelService(ctx context.Context, in *UnregisterModelServiceRequest, opts ...grpc.CallOption) (*UnregisterModelServiceResponse, error) {
	out := new(UnregisterModelServiceResponse)
	err := c.cc.Invoke(ctx, "/scheduler.Scheduler/UnregisterModelService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) RegisterGPUInstance(ctx context.Context, in *RegisterGPUInstanceRequest, opts ...grpc.CallOption) (*RegisterGPUInstanceResponse, error) {
	out := new(RegisterGPUInstanceResponse)
	err := c.cc.Invoke(ctx, "/scheduler.Scheduler/RegisterGPUInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
// All implementations must embed UnimplementedSchedulerServer
// for forward compatibility
type SchedulerServer interface {
	// Register a new model service
	RegisterModelService(context.Context, *RegisterModelServiceRequest) (*RegisterModelServiceResponse, error)
	// Scale a model service
	ScaleModelService(context.Context, *ScaleModelServiceRequest) (*ScaleModelServiceResponse, error)
	// Unregister a model service
	UnregisterModelService(context.Context, *UnregisterModelServiceRequest) (*UnregisterModelServiceResponse, error)
	// Register a new GPU instance
	RegisterGPUInstance(context.Context, *RegisterGPUInstanceRequest) (*RegisterGPUInstanceResponse, error)
	mustEmbedUnimplementedSchedulerServer()
}

// UnimplementedSchedulerServer must be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (UnimplementedSchedulerServer) RegisterModelService(context.Context, *RegisterModelServiceRequest) (*RegisterModelServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterModelService not implemented")
}
func (UnimplementedSchedulerServer) ScaleModelService(context.Context, *ScaleModelServiceRequest) (*ScaleModelServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScaleModelService not implemented")
}
func (UnimplementedSchedulerServer) UnregisterModelService(context.Context, *UnregisterModelServiceRequest) (*UnregisterModelServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterModelService not implemented")
}
func (UnimplementedSchedulerServer) RegisterGPUInstance(context.Context, *RegisterGPUInstanceRequest) (*RegisterGPUInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGPUInstance not implemented")
}
func (UnimplementedSchedulerServer) mustEmbedUnimplementedSchedulerServer() {}

// UnsafeSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServer will
// result in compilation errors.
type UnsafeSchedulerServer interface {
	mustEmbedUnimplementedSchedulerServer()
}

func RegisterSchedulerServer(s grpc.ServiceRegistrar, srv SchedulerServer) {
	s.RegisterService(&Scheduler_ServiceDesc, srv)
}

func _Scheduler_RegisterModelService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModelServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).RegisterModelService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.Scheduler/RegisterModelService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).RegisterModelService(ctx, req.(*RegisterModelServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ScaleModelService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleModelServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ScaleModelService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.Scheduler/ScaleModelService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ScaleModelService(ctx, req.(*ScaleModelServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_UnregisterModelService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterModelServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).UnregisterModelService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.Scheduler/UnregisterModelService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).UnregisterModelService(ctx, req.(*UnregisterModelServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_RegisterGPUInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGPUInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).RegisterGPUInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.Scheduler/RegisterGPUInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).RegisterGPUInstance(ctx, req.(*RegisterGPUInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduler_ServiceDesc is the grpc.ServiceDesc for Scheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterModelService",
			Handler:    _Scheduler_RegisterModelService_Handler,
		},
		{
			MethodName: "ScaleModelService",
			Handler:    _Scheduler_ScaleModelService_Handler,
		},
		{
			MethodName: "UnregisterModelService",
			Handler:    _Scheduler_UnregisterModelService_Handler,
		},
		{
			MethodName: "RegisterGPUInstance",
			Handler:    _Scheduler_RegisterGPUInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stub/scheduling.proto",
}
